branch-defaults:
  master:
    environment: arbitrage-app-dev
global:
  application_name: arbitrage-app
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
